"""Generate the 4-dataset main comparison table: Recall/NDCG @10/@20 across Amazon Baby/Sports/Clothing
+ MicroLens (16 metric columns; MAP dropped per layout choice, reported in prose). Bold=best in column,
underline=2nd. MV-MoE row + a separate +/-3SE row. Emits LaTeX rows to stdout.
Sources: crossarch_knockout.json (Amazon baselines), repro_metrics.json (Amazon LightGCN),
finalize.json (Amazon MV-MoE), microlens_baselines.json (MicroLens 13 baselines),
finalize_microlens.json (MicroLens MV-MoE)."""
import json
from pathlib import Path

R = Path("/workspace/MechInterp")
cross = json.load(open(R / "results/phasex_crossarch/crossarch_knockout.json"))
repro = json.load(open(R / "results/phase0/repro_metrics.json"))
finA = json.load(open(R / "results/bai/finalize.json"))
mlB = json.load(open(R / "results/bai/microlens_baselines.json"))
finM = json.load(open(R / "results/bai/finalize_microlens.json"))

DS = ["baby", "sports", "clothing", "microlens"]
MET = ["Recall@10", "Recall@20", "NDCG@10", "NDCG@20"]
MODELS = ["lightgcn", "vbpr", "mmgcn", "lattice", "bm3", "mgcn", "mentor",
          "freedom", "lgmrec", "damrs", "smore", "cohesion", "gume", "MV-MoE"]
DISP = {"lightgcn": "LightGCN", "vbpr": "VBPR", "mmgcn": "MMGCN", "lattice": "LATTICE",
        "bm3": "BM3", "mgcn": "MGCN", "mentor": "MENTOR", "freedom": "FREEDOM",
        "lgmrec": "LGMRec", "damrs": "DAMRS", "smore": "SMORE", "cohesion": "COHESION",
        "gume": "GUME", "MV-MoE": "\\textbf{MV-MoE}"}

cl = {(r["model"], r["dataset"]): r["baseline"] for r in cross}
rl = {(r["model"], r["dataset"]): r["recomputed"] for r in repro}

V = {m: {} for m in MODELS}
for m in MODELS:
    for ds in DS:
        if ds == "microlens":
            V[m][ds] = finM["bag"] if m == "MV-MoE" else mlB[m]
        elif m == "MV-MoE":
            V[m][ds] = finA[ds]["bag"]
        elif m == "lightgcn":
            V[m][ds] = rl[(m, ds)]
        else:
            V[m][ds] = cl[(m, ds)]

rank = {}
for ds in DS:
    for met in MET:
        vals = sorted(((V[m][ds][met], m) for m in MODELS), reverse=True)
        rank[(ds, met)] = (vals[0][1], vals[1][1])


def cell(m, ds, met):
    v = V[m][ds][met]; s = f"{v:.4f}"
    best, sec = rank[(ds, met)]
    if m == best:
        return f"\\textbf{{{s}}}" if m != "MV-MoE" else f"\\textbf{{{s}}}"
    if m == sec:
        return f"\\underline{{{s}}}"
    return s


print("% --- auto-generated by gen_main_table_v2.py ; do not hand-edit numbers ---")
for m in MODELS:
    cells = [cell(m, ds, met) for ds in DS for met in MET]
    line = DISP[m] + " & " + " & ".join(cells) + "\\\\"
    if m == "MV-MoE":
        print("\\midrule")
        line = DISP[m] + "$^{*}$ & " + " & ".join(cells) + "\\\\"
    print(line)

# +/-3SE row (MV-MoE), 16 cols
se = []
for ds in DS:
    src = finM["three_SE"] if ds == "microlens" else finA[ds]["three_SE"]
    for met in MET:
        se.append(f"{src[met]:.4f}"[1:])  # drop leading 0 -> .0008
print("\\;{\\tiny$\\pm3$\\,SE} & " + " & ".join(f"{{\\tiny{x}}}" for x in se) + "\\\\")

# console summary: improvement of MV-MoE vs best baseline per dataset (R@20), + MAP for prose
print("\n% ---- prose helpers ----")
for ds in DS:
    bb = max((V[m][ds]["Recall@20"], m) for m in MODELS if m != "MV-MoE")
    mv = V["MV-MoE"][ds]["Recall@20"]
    print(f"% {ds}: MV-MoE R@20={mv:.4f} vs best baseline {bb[1]} {bb[0]:.4f}  (+{100*(mv-bb[0])/bb[0]:.1f}%)")
# MAP improvements (for the prose sentence)
for ds in DS:
    src_bag = finM["bag"] if ds == "microlens" else finA[ds]["bag"]
    gume = V["gume"][ds]
    for k in ("MAP@10", "MAP@20"):
        if k in src_bag and k in gume:
            print(f"% {ds} {k}: MV-MoE {src_bag[k]:.4f} vs GUME {gume[k]:.4f} (+{100*(src_bag[k]-gume[k])/gume[k]:.1f}%)")
