"""Generate the expanded main comparison table (LaTeX rows) from real artifacts.
Metrics: Recall@10/20, NDCG@10/20, Precision@10/20 on Amazon Baby/Sports/Clothing.
Sources: crossarch_knockout.json (12 MM baselines + GUME), repro_metrics.json (LightGCN),
mvmoe_fullmetrics.json (MV-MoE). Bold = best in column, underline = 2nd best.
"""
import json
from pathlib import Path

R = Path("/workspace/MechInterp")
cross = json.load(open(R / "results/phasex_crossarch/crossarch_knockout.json"))
repro = json.load(open(R / "results/phase0/repro_metrics.json"))
fin = json.load(open(R / "results/bai/finalize.json"))   # 5-seed bag + three_SE + improv + sig
mvmoe = {ds: fin[ds]["bag"] for ds in fin}

DS = ["baby", "sports", "clothing"]
MET = ["Recall@10", "Recall@20", "NDCG@10", "NDCG@20", "MAP@10", "MAP@20"]
ROWS = ["lightgcn", "vbpr", "mmgcn", "lattice", "bm3", "mgcn", "mentor",
        "freedom", "lgmrec", "damrs", "smore", "cohesion", "gume", "MV-MoE"]
DISP = {"lightgcn": "LightGCN", "vbpr": "VBPR", "mmgcn": "MMGCN", "lattice": "LATTICE",
        "bm3": "BM3", "mgcn": "MGCN", "mentor": "MENTOR", "freedom": "FREEDOM",
        "lgmrec": "LGMRec", "damrs": "DAMRS", "smore": "SMORE", "cohesion": "COHESION",
        "gume": "GUME", "MV-MoE": "\\textbf{MV-MoE}"}

# value table V[model][ds][metric]
V = {m: {} for m in ROWS}
cl = {(r["model"], r["dataset"]): r["baseline"] for r in cross}
rl = {(r["model"], r["dataset"]): r["recomputed"] for r in repro}
for m in ROWS:
    for ds in DS:
        if m == "MV-MoE":
            V[m][ds] = mvmoe[ds]
        elif (m, ds) in cl:
            V[m][ds] = cl[(m, ds)]
        elif (m, ds) in rl:
            V[m][ds] = rl[(m, ds)]
        else:
            raise SystemExit(f"missing {m}/{ds}")

# best / 2nd-best per (ds,metric)
rank = {}
for ds in DS:
    for met in MET:
        vals = sorted(((V[m][ds][met], m) for m in ROWS), reverse=True)
        rank[(ds, met)] = (vals[0][1], vals[1][1])  # best, second

def cell(m, ds, met):
    v = V[m][ds][met]
    s = f"{v:.4f}"
    best, second = rank[(ds, met)]
    if m == best:
        if m == "MV-MoE":
            se = f"{fin[ds]['three_SE'][met]:.4f}"[1:]   # drop leading 0 -> .0008
            return f"\\textbf{{{s}}}$_{{\\pm{se}}}$"
        return f"\\textbf{{{s}}}"
    if m == second:
        return f"\\underline{{{s}}}"
    return s

# emit rows
print("% --- auto-generated by gen_main_table.py ; do not hand-edit numbers ---")
for m in ROWS:
    cells = []
    for ds in DS:
        for met in MET:
            cells.append(cell(m, ds, met))
    line = DISP[m] + " & " + " & ".join(cells) + "\\\\"
    if m == "MV-MoE":
        print("\\midrule")
    print(line)

# Improv.% row (MV-MoE vs best baseline = GUME), LaTeX-ready
impcells = []
for ds in DS:
    for met in MET:
        impcells.append(f"+{fin[ds]['improv_vs_gume'][met]:.1f}")
print("\\;Improv.\\% & " + " & ".join(impcells) + "\\\\")
# significance summary
allsig = all(fin[ds]["sig"][met]["sig"] for ds in DS for met in MET)
print(f"% all 18 cells significant (p<0.05): {allsig}")
# who is the best baseline overall (R@20)
for ds in DS:
    bb = max(((V[m][ds]["Recall@20"], m) for m in ROWS if m != "MV-MoE"))
    print(f"% best baseline R@20 {ds}: {bb[1]} {bb[0]:.4f}")
